name: Build with Android NDK Clang

on: [push]

jobs:
  BuildBinaries:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Install Android SDK Command-Line Tools
      - name: Install Android SDK Command-Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/temp
          mv $HOME/android-sdk/cmdline-tools/temp/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          rm -rf $HOME/android-sdk/cmdline-tools/temp cmdline-tools.zip

      - name: Accept SDK Licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      # Install NDK and Clang
      - name: Install NDK and Platform Tools
        run: |
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-33" "ndk;27.2.12479018" "cmake;3.31.0" "build-tools;30.0.3"
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk

      # Set up environment variables
      - name: Set Environment Variables
        run: |
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$ANDROID_SDK_ROOT/platform-tools:\$PATH" >> $GITHUB_ENV
          echo "export NDK_HOME=\$ANDROID_SDK_ROOT/ndk/27.1.6" >> $GITHUB_ENV
          echo "export PATH=\$NDK_HOME:\$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:\$PATH" >> $GITHUB_ENV
        shell: bash

      # Ensure ndk-build is available
      - name: Verify ndk-build Path
        run: |
          if [ ! -f "$NDK_HOME/ndk-build" ]; then
            echo "ndk-build not found in $NDK_HOME"
            exit 1
          fi
          chmod +x $NDK_HOME/ndk-build
          echo "ndk-build found and is executable"

      # Build using ndk-build
      - name: Build Project with ndk-build
        run: |
          ndk-build NDK_PROJECT_PATH=./android_toolchain clean
          ndk-build NDK_PROJECT_PATH=./android_toolchain
