name: Build with Android NDK Clang

on: [push]

jobs:
  BuildBinaries:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Install the Android SDK and NDK
      - name: Install Android SDK Command-Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/latest
          rm cmdline-tools.zip


      - name: Accept SDK Licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install NDK and Clang
        run: |
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-33" "ndk;27.1.6" "build-tools;33.0.2"
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk

      # Set up environment variables
      - name: Set Environment Variables
        run: |
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$ANDROID_SDK_ROOT/platform-tools:\$PATH" >> $GITHUB_ENV
          echo "export NDK_HOME=\$ANDROID_SDK_ROOT/ndk/27.1.6" >> $GITHUB_ENV
          echo "export PATH=\$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:\$PATH" >> $GITHUB_ENV
        shell: bash

      # Build using ndk-build
      - name: Build Project with ndk-build
        run: |
          ndk-build NDK_PROJECT_PATH=./android_toolchain clean
          ndk-build NDK_PROJECT_PATH=./android_toolchain
