name: default

on: [push]

jobs:
  BuildBinaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
      - run: ndk-build clean; ndk-build NDK_PROJECT_PATH=./android_toolchain
